### ISSUE TITLE
where to find the "metadata.tsv" and ""/metadata.mut_long.tsv" files?

### ISSUE THREAD

**Issue by liamxg** [TheSatoLab/KP.2_short#1]
Dear @ninjin-cake,

Could you tell me where to find the "metadata.tsv" and ""/metadata.mut_long.tsv" files?

**Comment by ninjin-cake** [comment]
Dear @liamxg,
Thank you for the message.
The metadata file “metadata.tsv” had been downloaded from GISAID via “Download packages”. Unfortunately, according to the data sharing policy of GISAID, we cannot re-distribute this file.
With the “metadata.tsv” file, please run the summarize_mut_info.ver2.py that we have just uploaded on KP.2_short folder.
Apologies for the inconvenience.
Best wishes

**Comment by liamxg** [comment]
Hi @ninjin-cake,

Thanks. after run the `summarize_mut_info.ver2.py` file using `metadata.tsv` file as input, I get `metadata.mut_long.tsv` file, right?

**Comment by ninjin-cake** [comment]
Dear @liamxg,
Yes, I believe that would work.
Best regards

**Comment by liamxg** [comment]
@ninjin-cake,
Cool, thanks.
