### ISSUE TITLE
Assertion on 'stan_file' failed: File does not exist: ''.

### ISSUE THREAD

**Issue by liamxg** [TheSatoLab/KP.2_short#2]
Dear @ninjin-cake 

When I run the `multi_nomial_model <- cmdstan_model(stan_f.name)`, it prints as below:
<img width="591" alt="image" src="https://github.com/TheSatoLab/KP.2_short/assets/46078579/faf32821-d709-45dd-9b8b-327f217c75ef">

**Comment by ninjin-cake** [comment]
Dear @liamxg 

We have uploaded an additional file to the KP.2_short folder. 
Please try using the multinomial_independent.ver2.stan file.
For more detail, I believe cmdstanr page https://mc-stan.org/cmdstanr/ would also help.

Thanks

**Comment by liamxg** [comment]
thanks.
